### ISSUE TITLE
New additions

### ISSUE THREAD

**Issue by czyzby** [rafaskb/awesome-libgdx#19]
Thank you for maintaining this list! Here's a couple of suggestions that you could include in the repo:

### User interface
- [gdx-lml](https://github.com/czyzby/gdx-lml/tree/master/lml) - HTML-like markup language for Scene2D GUI.

### Visual effects
- [Talos](https://github.com/rockbite/talos) - VFX Editor.

### Languages support
- [KTX](https://github.com/libktx/ktx) - Kotlin extensions and utilities for LibGDX.
- [play-clj](https://github.com/oakes/play-clj) - Clojure LibGDX wrapper.

### Others
- [gdx-kiwi](https://github.com/czyzby/gdx-lml/tree/master/kiwi) - various LibGDX utilities.
- [gdx-websocket](https://github.com/czyzby/gdx-lml/tree/master/websocket) - multi-platform WebSocket client.

**Comment by rafaskb** [comment]
Hey @czyzby! Sorry for taking so long to reply. Thank you for putting the time to make new suggestions to the list. :)

# Talos
This is a **very** impressive project and will definitely be added to the list, but right now it's really unstable and not many users have vouched for it yet. It will be added when it's mature and stable enough.

# KTX
KTX seems like a wonderful project! Is it a different framework or does it still use regular libGDX behind the scenes? Either way I think it should be added to the list, but I'll run it by other developers in the libGDX Discord first, preferably Kotlin ones.

# play-clj
This repository was archived, so unfortunately it's probably abandoned by now.

# gdx-lml and subprojects
These too sound like amazing additions to the list, especially lml, but the _"These libraries are no longer actively maintained. [...] Expect issues with recent [libGDX versions]."_ disclaimer in the first line of the README file makes it impossible for them to be added to the list, as the intention is to keep all resources as updated as possible.

I noticed metaphore updated some of the subprojects to use the latest libGDX version, but the disclaimer was added after that, so I guess we can add them (with the community's approval, as always) as long as they're actively maintained.

**Comment by czyzby** [comment]
> KTX seems like a wonderful project! Is it a different framework or does it still use regular libGDX behind the scenes?
KTX provides various Kotlin extensions for the LibGDX framework, so yes - is still uses regular LibGDX under the hood and encourages the users to do so. You can think of it as Kotlin language support added for the LibGDX APIs without making them unrecognizable. It's much less invasive than e.g. [mini2Dx](https://mini2dx.org/).

**Comment by rafaskb** [comment]
KTX has been added to the list! :)

**Comment by czyzby** [comment]
Well, gdx-websocket is pretty independent of the LibGDX version, so while not actively maintained, afaik it should work with the latest LibGDX and I think it's still the best option if you need a cross-platform websocket client. (But obviously I'm biased, since it's my library. ;)) I understand why you'd prefer to omit gdx-lml and gdx-kiwi - but if there's anything that's worth keeping out of that repo, it's definitely the websockets library.

You can close this issue. :)
