### ISSUE TITLE
libGDX hardware cursor

### ISSUE THREAD

**Issue by dzikoysk** [rafaskb/awesome-libgdx#26]
Hey, what do you think about linking these snippets:
* libGDX with LWJGL2 backend: https://gist.github.com/dzikoysk/0b77744386a659bb7ead629f53830bfd
* libGDX with LWJGL3 backend: https://gist.github.com/dzikoysk/b0e2f24048f8fee0ab9253d9d7ab9aa3

The following code allows us to use hardware cursor clipped in window on Windows. It reduces popular input lag caused by standard cross-platform catching api.

**Comment by rafaskb** [comment]
Sounds like a great feature! However it should be a PR to the official libGDX repo in my opinion, not a library per see.

**Comment by dzikoysk** [comment]
We've discussed about it on libGDX discord and we came to the conclusion that it's not really possible to support this by libGDX due to platform-specific use case of this solution. I've linked it here to leave a trace for people struggling with this unresolved issue, even as a closed topic here. I'm pretty sure that someone may find it really helpful in the future.
