### ISSUE TITLE
Suggestion for a new entry to the tutorials section

### ISSUE THREAD

**Issue by florestankorp** [rafaskb/awesome-libgdx#31]
- [Space Shooter Game](https://www.youtube.com/watch?v=DK1sGc4rOT4&list=PLfd-5Q3Fwq0WKrkEKw12nqpfER3MG5_Wi) - Graphics in Android Java with libGDX.

**Comment by rafaskb** [comment]
Thank you for your contribution! The tutorial series have been added to the list. 😁
