### ISSUE TITLE
Suggestion for new entry

### ISSUE THREAD

**Issue by ChristianPervoelz** [rafaskb/awesome-libgdx#37]
Hi,

could you imagine to add [this little library](https://github.com/ChristianPervoelz/LibGDX-ScreenSwitch) to your list?

It provides some easy to setup transitions for scene2d screens of libgdx.

Thanks
Christian

**Comment by rafaskb** [comment]
Hi! The library seems very useful, but it seems like there haven't been any changes recently and its not mature enough yet. Feel free to open a PR for it once more devs start using it though 😁
